// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBictoqBkjWL5sRU454igfGHjB1Zkjtdbg',
    appId: '1:989620708555:web:a3dc86a87458925558274e',
    messagingSenderId: '989620708555',
    projectId: 'helloapp-391dd',
    authDomain: 'helloapp-391dd.firebaseapp.com',
    storageBucket: 'helloapp-391dd.appspot.com',
    measurementId: 'G-B10Y1GF0XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzylDTr2p-xY8pJYxbG8HO1TMYh29fRI',
    appId: '1:989620708555:android:900e351b1567375d58274e',
    messagingSenderId: '989620708555',
    projectId: 'helloapp-391dd',
    storageBucket: 'helloapp-391dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1dj5sGOepuxdoAj_-mTZeYdi1gyFtXvM',
    appId: '1:989620708555:ios:43ac73a2b45492f858274e',
    messagingSenderId: '989620708555',
    projectId: 'helloapp-391dd',
    storageBucket: 'helloapp-391dd.appspot.com',
    iosBundleId: 'com.example.helloapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1dj5sGOepuxdoAj_-mTZeYdi1gyFtXvM',
    appId: '1:989620708555:ios:be575be26e6b7a4058274e',
    messagingSenderId: '989620708555',
    projectId: 'helloapp-391dd',
    storageBucket: 'helloapp-391dd.appspot.com',
    iosBundleId: 'com.example.helloapp.RunnerTests',
  );
}
